### PR TITLE
fix message in debug message

### PR DESCRIPTION
**Pull request by rileytg**
not sure if i am capturing the logic correctly..

### CODE REVIEW

**Comment by dhiaayachi** [comment]
Thank you for fixing this @rileytg

I noticed that the error message in [here](https://github.com/hashicorp/raft-autopilot/blob/fef4cb69e6558106c750881921fd5295d74d718e/reconcile.go#L258) is also not correct, can you please fix it as part of this PR

**Comment by dhiaayachi** [comment]
Thank you for fixing this @rileytg

I noticed that the error message in [here](https://github.com/hashicorp/raft-autopilot/blob/fef4cb69e6558106c750881921fd5295d74d718e/reconcile.go#L258) is also not correct, can you please fix it as part of this PR

**Comment by rileytg** [comment]
updated @dhiaayachi

**Review by dhiaayachi — APPROVED** [review]
LGTM!! 
Thank you @rileytg

**Pull request merged**
